name: zaps_scorer
description: ZAPS Riichi Mahjong Scorer

# build name+build number.
# build name is N.N.N, and is otherwise completely flexible.
# build number is N, and must be strictly monotonic increasing
version: 0.1.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  alice: # ^0.0.4
  auto_size_text: # ^1.1.2
  card_settings: # ^1.4.1
  flutter_redux: # ^0.5.3
  flutter_typeahead: # ^1.5.0
  http: # ^0.12.0
  path: # ^1.6.2
  path_provider: # ^1.1.0
  pin_input_text_field: # ^0.3.1
  redux: # ^3.0.0
  reorderables: # ^0.2.7
  shared_preferences: # ^0.5.2
  sqflite: # ^1.1.5

  flutter:
    sdk: flutter

  cupertino_icons: # ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


